# Logistic Regression Implimentation(classificaton problem)

In [24]:
from sklearn.datasets import load_iris

In [28]:
dataset=load_iris()

In [29]:
print(dataset.DESCR)


.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [32]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [33]:
#importing libraries

In [34]:
import pandas as pd
import numpy as np

In [41]:
df=pd.DataFrame(dataset.data,columns=dataset.feature_names)

In [42]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [43]:
dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [44]:
df["target"]=dataset.target

In [45]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [46]:
# This is a classification problem so we need to have only two categories but here you can see

In [50]:
df["target"].unique() # there are 3 categories

array([0, 1, 2])

In [51]:
#first we wil only take first 0 and 1 and train the model using logistic regresssion.

In [52]:
df_copy=df[df["target"]!=2]

In [54]:
df_copy.head() #now i have only 0 and 1 records

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [56]:
df_copy["target"].unique()

array([0, 1])

In [57]:
from sklearn.model_selection import train_test_split

In [60]:
#independent and dependent features

In [64]:
X=df_copy.iloc[:,:-1]
y=df_copy.iloc[:,-1]

In [65]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)

In [67]:
#imnporting logistic regression

In [68]:
from sklearn.linear_model import LogisticRegression

In [73]:
classfication=LogisticRegression(max_iter=200)

In [74]:
classfication

LogisticRegression(max_iter=200)

In [75]:
classfication.fit(X_train,y_train)

LogisticRegression(max_iter=200)

In [76]:
y_pred=classfication.predict(X_test)

In [77]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

## Confusion Metrics,Accuracy,Classification Report

In [78]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [79]:
print(confusion_matrix(y_test,y_pred))

[[12  0]
 [ 0  8]]


In [81]:
print(accuracy_score(y_test,y_pred)) # here will get 100% only because there is not fp or fn

1.0


In [82]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



## Cross-Validation

In [98]:
from sklearn.model_selection import KFold #we interanally divide train data into train and validation
#calculate different accuracy

In [90]:
cv=KFold(n_splits=5)

In [91]:
cv

KFold(n_splits=5, random_state=None, shuffle=False)

In [92]:
from sklearn.model_selection import cross_val_score

In [95]:
# scores of all the cross validation
scores=cross_val_score(classfication,X_train,y_train,scoring='accuracy',cv=cv)

In [96]:
scores

array([1., 1., 1., 1., 1.])

In [97]:
np.mean(scores)

1.0

In [99]:
## lets try more complex data

In [103]:
# make a prediction with a multinomial logistic regression model
from sklearn.datasets import make_classification #for making own dataset
from sklearn.linear_model import LogisticRegression
# define dataset


In [105]:
X,y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=2, random_state=1)

In [108]:
from sklearn.model_selection import train_test_split

In [109]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)

In [113]:
complex_class=LogisticRegression(max_iter=200)

In [115]:
complex_class.fit(X_train,y_train)

LogisticRegression(max_iter=200)

In [116]:
complex_y_pred=complex_class.predict(X_test)

In [117]:
complex_y_pred

array([0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 1])

In [118]:
print(confusion_matrix(y_test,complex_y_pred))
print(accuracy_score(y_test,complex_y_pred))
print(classification_report(y_test,complex_y_pred))


[[78 13]
 [29 80]]
0.79
              precision    recall  f1-score   support

           0       0.73      0.86      0.79        91
           1       0.86      0.73      0.79       109

    accuracy                           0.79       200
   macro avg       0.79      0.80      0.79       200
weighted avg       0.80      0.79      0.79       200



In [119]:
# here there are so many errors 13 fp and 29 fn and accuracy is 79%

Now the thing is can we increase the accuracy??

In [120]:
#lets check with performing cv internally

In [121]:
#cross validation

In [122]:
cv=KFold(n_splits=5)

In [126]:
scores_complex=cross_val_score(complex_class,X_train,y_train,cv=cv)

In [127]:
np.mean(scores_complex)

0.8099999999999999

# Logistic Regression with Hyperparamter Tuning

The main aim of hyperparameter tuning is to select the paramters for the specific given datase to get the best paramters.
Here we are using hyperparameter tuning with GridsearchCv

In [128]:
# creating a complex datset first

In [130]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression

In [131]:
X,y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=2, random_state=1)

In [132]:
from sklearn.model_selection import train_test_split

In [133]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)

### model training hyperprameter tuning
### GridsearchCV

In [140]:
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings("ignore")

In [142]:
parameters={"penalty":("l1","l2","elasticnet"),"C":[1,20,30]  } #params shopuld be given in tuple and numbers in []

In [143]:
classifier=LogisticRegression()

In [145]:
clf=GridSearchCV(classifier,param_grid=parameters,cv=5)


In [146]:
clf

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 20, 30],
                         'penalty': ('l1', 'l2', 'elasticnet')})

Here Gridsearchcv will check all the possibilities and and accuracies and give the best parameters for the high accuracy.

In [ ]:
#model training
# here only splitting of training data to train and validation happens internally

In [147]:
clf.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 20, 30],
                         'penalty': ('l1', 'l2', 'elasticnet')})

In [149]:
clf.best_params_ # these are best params were selected for model traning

{'C': 1, 'penalty': 'l2'}

In [150]:
clf.best_score_

0.8087500000000001

In [151]:
classifier=LogisticRegression(C=1,penalty="l2")

In [152]:
classifier

LogisticRegression(C=1)

In [154]:
classifier.fit(X_train,y_train) #model created

LogisticRegression(C=1)

In [156]:
y_pred=classifier.predict(X_test)

In [157]:
y_pred

array([0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 1])

In [161]:
classifier.predict_proba(X_test) #here 71% is telling that it belongs to 0 category.

array([[0.71649202, 0.28350798],
       [0.19508969, 0.80491031],
       [0.12418141, 0.87581859],
       [0.05045906, 0.94954094],
       [0.88775659, 0.11224341],
       [0.75067497, 0.24932503],
       [0.97980488, 0.02019512],
       [0.3921745 , 0.6078255 ],
       [0.59920135, 0.40079865],
       [0.39295203, 0.60704797],
       [0.20428696, 0.79571304],
       [0.80257879, 0.19742121],
       [0.86422932, 0.13577068],
       [0.92665682, 0.07334318],
       [0.00131743, 0.99868257],
       [0.04171096, 0.95828904],
       [0.56288536, 0.43711464],
       [0.89322764, 0.10677236],
       [0.29278211, 0.70721789],
       [0.00870994, 0.99129006],
       [0.71879454, 0.28120546],
       [0.5108267 , 0.4891733 ],
       [0.76230298, 0.23769702],
       [0.73170811, 0.26829189],
       [0.10155737, 0.89844263],
       [0.04046512, 0.95953488],
       [0.57926768, 0.42073232],
       [0.00526468, 0.99473532],
       [0.03101648, 0.96898352],
       [0.96093035, 0.03906965],
       [0.

In [163]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [165]:
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[78 13]
 [29 80]]
0.79
              precision    recall  f1-score   support

           0       0.73      0.86      0.79        91
           1       0.86      0.73      0.79       109

    accuracy                           0.79       200
   macro avg       0.79      0.80      0.79       200
weighted avg       0.80      0.79      0.79       200



## Randomized Search cv

In [166]:
from sklearn.model_selection import RandomizedSearchCV

In [167]:
random_clf=RandomizedSearchCV(LogisticRegression(),param_distributions=parameters,cv=5,n_iter=20)

In [168]:
random_clf

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_iter=20,
                   param_distributions={'C': [1, 20, 30],
                                        'penalty': ('l1', 'l2', 'elasticnet')})

In [169]:
random_clf.fit(X_train,y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_iter=20,
                   param_distributions={'C': [1, 20, 30],
                                        'penalty': ('l1', 'l2', 'elasticnet')})

In [170]:
random_clf.best_params_

{'penalty': 'l2', 'C': 1}